version: "3.8"

services:
  attendance-db:
    image: mysql
    container_name: attendance-db
    restart: always
    environment:
      MYSQL_DATABASE: student_attendance
      MYSQL_ROOT_PASSWORD: 12345678@QuocAnh
    ports:
      - "3868:3306"
    volumes:
      - attendance_data:/var/lib/mysql

  attendance-fe:
    image: quocanhh86/fpl-student-attendance-fe:multi-arch
    container_name: attendance-fe
    restart: always
    ports:
      - "80:80"
    depends_on:
      - attendance-be

  attendance-be:
    image: quocanhh86/fpl-student-attendance-be:multi-arch
    container_name: attendance-be
    restart: always
    ports:
      - "8765:8765"
    environment:
      MYSQL_HOST: attendance-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: student_attendance
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678@QuocAnh
      JPA_SHOW_SQL: "false"
      JPA_DDL_AUTO: update

      DB_GENERATOR: "true"
      DB_USER_NAME: Nguyễn Quốc Anh
      DB_USER_CODE: TH01267
      DB_USER_EMAIL: quocanhn352@gmail.com
      DB_FACILITY_NAME: Hà nội, Hồ chí minh

      GOOGLE_CLIENT_ID: 297963940212-0805h66ooagrpa4mon9e34kdigetu4cs.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_SCOPE: email,profile

      AUTHENTICATION_SECRET_KEY: 0805h66ooagrpa4mon9e34kdigetu4cs0805h66ooagrpa4mon9e34kdigetu4cs

      MAILER_USERNAME: examdistribution@gmail.com
      MAILER_PASSWORD: wycvtgbsnnpdofzj
      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 587

      SERVER_PORT: 8765
      SERVER_ALLOWED_ORIGIN: http://fptudpm.site
      APP_CONFIG_DISABLED_CHECK_EMAIL_FPT: "true"
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - attendance-db

volumes:
  attendance_data:


networks:
  xth-dev-udpm-networks:
    external: true
