package udpm.hn.studentattendance.repositories;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import udpm.hn.studentattendance.entities.Factory;
import udpm.hn.studentattendance.infrastructure.config.TestDatabaseConfig;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import org.springframework.context.annotation.Import;

@DataJpaTest
@ExtendWith(SpringExtension.class)
@Import(TestDatabaseConfig.class)
class FactoryRepositoryTest {

    @Autowired
    private FactoryRepository factoryRepository;

    @Test
    void testSaveAndFindById() {
        Factory factory = new Factory();
        factory.setName("Test Factory");
        factory.setDescription("A test factory");
        // id is generated by PrimaryEntity (assume it's a String UUID or similar)
        Factory saved = factoryRepository.save(factory);
        assertNotNull(saved.getId());

        Optional<Factory> found = factoryRepository.findById(saved.getId());
        assertTrue(found.isPresent());
        assertEquals("Test Factory", found.get().getName());
        assertEquals("A test factory", found.get().getDescription());
    }
}
