export default {
  async: true,
  modelBasePath: '/models/human',
  cacheModels: true,
  cacheSensitivity: 0.01,
  debug: false,
  face: {
    enabled: true,
    detector: {
      rotation: true,
      inputSize: 448,
      maxDetected: 1,
      iouThreshold: 0.2,
      minConfidence: 0.7,
      square: true,
    },
    iris: { enabled: false },
    description: { enabled: true },
    embedding: { enabled: true },
    emotion: { enabled: true },
    mesh: { enabled: true },
    antispoof: { enabled: false },
    liveness: { enabled: false },
  },
  body: { enabled: false },
  hand: { enabled: false },
  object: { enabled: false },
  gesture: { enabled: true },
}
